name: Viper
configs:
  Debug: debug
  Develop: develop
  Staging: staging
  Release: release
options:
  bundleIdPrefix: Masanao-Imai
  deploymentTarget:
    iOS: '11.0'
settings:
  base:
    SWIFT_VERSION: 5.0
    PRODUCT_NAME: $TARGET_NAME
    CURRENT_PROJECT_VERSION: 1
schemes:
  Viper:
    build:
      targets:
        Viper: all
        ViperTests: [test]
        ViperUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Develop
    analyze:
      config: Develop
    archive:
      config: Develop
  Viper-staging:
    build:
      targets:
        Viper: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Staging
    analyze:
      config: Debug
    archive:
      config: Staging
  Viper-store:
    build:
      targets:
        Viper: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
targets:
  Viper:
    type: application
    platform: iOS
    sources: Viper
    settings:
      CODE_SIGN_STYLE: Manual
      INFOPLIST_FILE: Viper/Info.plist
    dependencies:
      - carthage: Kingfisher
      - carthage: Reusable
    configs:
      Debug:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        CODE_SIGN_IDENTITY: iPhone Developer
        DEVELOPMENT_TEAM: K82438J7JC
        PRODUCT_BUNDLE_IDENTIFIER: Masanao-Imai.Viper
        PRODUCT_NAME: $TARGET_NAME
      Develop:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEVELOP
        CODE_SIGN_IDENTITY: iPhone Distribution
        DEVELOPMENT_TEAM: K82438J7JC
        PRODUCT_BUNDLE_IDENTIFIER: Masanao-Imai.Viper
        PRODUCT_NAME: $TARGET_NAME
      Staging:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: STAGING
        CODE_SIGN_IDENTITY: iPhone Distribution
        DEVELOPMENT_TEAM: K82438J7JC
        PRODUCT_BUNDLE_IDENTIFIER: Masanao-Imai.Viper
        PRODUCT_NAME: $TARGET_NAME
      Release:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
        CODE_SIGN_IDENTITY: iPhone Distribution
        PRODUCT_BUNDLE_IDENTIFIER: Masanao-Imai.Viper
        PRODUCT_NAME: $TARGET_NAME
    scheme:
      testTargets:
        - ViperTests
        - ViperUITests
    prebuildScripts:
      - name: Run SwiftFormat
        script: |
          if which mint >/dev/null; then
          mint run swiftformat swiftformat .
          else
          echo "warning: Mint not installed, download from https://github.com/yonaskolb/Mint"
          fi
      - name: Run SwiftLint
        script: |
          if which mint >/dev/null; then
          mint run swiftlint swiftlint
          else
          echo "warning: Mint not installed, download from https://github.com/yonaskolb/Mint"
          fi
      - name: Run SwiftGen
        script: |
          if which mint >/dev/null; then
          mint run swiftgen swiftgen
          else
          echo "warning: Mint not installed, download from https://github.com/yonaskolb/Mint"
          fi
  ViperTests:
    type: bundle.unit-test
    platform: iOS
    sources: ViperTests
    dependencies:
      - target: Viper
  ViperUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: ViperUITests
    dependencies:
      - target: Viper
